version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: symfony7_db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - symfony7

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: symfony7_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8086:80
        environment:
            PMA_HOST: db
        networks:
            - symfony7

    # Symfony apache project container
    www:
        build: docker/php
        container_name: symfony7_symfony
        ports:
          - "8742:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - symfony7

networks:
    symfony7:

volumes:
    db-data: